# Generated by Django 5.0.6 on 2024-06-03 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_type', models.CharField(choices=[('ALIEN', 'Alien'), ('MUTANT', 'Mutant'), ('HUMAN', 'Human'), ('ROBOT', 'Robot')], max_length=50)),
                ('power', models.CharField(max_length=100)),
                ('weakness', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
