# Generated by Django 5.0.6 on 2024-06-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.ImageField(default=1, upload_to='superheros/'),
            preserve_default=False,
        ),
    ]
