# Generated by Django 5.0.6 on 2024-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marvel', '0002_superhero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='hero_type',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='power',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='weakness',
        ),
        migrations.AddField(
            model_name='superhero',
            name='type',
            field=models.CharField(choices=[('hero', 'Hero'), ('villain', 'Villain')], default='hero', max_length=50),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(upload_to='chais/'),
        ),
    ]
